version: "3.9"

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "back-end-tvshow"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  postgres:
